
spring:
    application:
        name: methaphorce
    profiles:
        active: dev
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER    
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'        

