
spring:
    profiles:
        active: h2-database
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER    
        
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'        

---
#LOCAL PROPERTIES
#spring.sql.init.mode=always
spring:
   profiles: h2-database
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: update
      show-sql: true   
      defer-datasource-initialization: true 
   datasource:
       driverClassName: org.h2.Driver
#       url: jdbc:h2:mem:methaphorce;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
       url: jdbc:h2:file:~/tmp/methaphorce;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
       username: sa
       password:
   h2:
      console:
         enabled: true
        
---       
# Local properties
spring:
    profiles: localMysql
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/methaphorce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: osva
    jpa:
        hibernate:
            ddl-auto: update    
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                format_sql: true
                
#        show-sql: true
        

